# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Créaphé
tagline:          Association
description:      
url:              http://www.creaphe.com

# Navigation
navigation:
- title: Home
  url: http://alexblanquart.github.io/creaphe/
- title: Notre projet
  url: http://alexblanquart.github.io/creaphe/about.html

author:
  name:           Alexandre Blanquart
  url:            

paginate:         1

# Custom vars
version:          0.0.1

github:
  repo:           
